version: "3.8"

services:
  app:
    build: .
    container_name: next_app
    restart: always
    env_file: .env
    ports:
      - "3000:3000"

  nginx:
    image: nginx:1.25-alpine
    container_name: nginx_proxy
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./public:/app/public
    depends_on:
      - app
